# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_user_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
