# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20170910_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_by',
        ),
    ]
