# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20170910_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
