# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='color',
            field=models.CharField(choices=[('#08aae6', 'Blue'), ('#00C851', 'Green'), ('#ff3547', 'Red'), ('#880e4f', 'Purple'), ('#F80', 'Orange')], max_length=50, null=True),
        ),
    ]
